### ISSUE TITLE
SUPER Arbeit!

### ISSUE THREAD

**Issue by Matten-Matten** [Thorsten2605/node-red-neato-botvac#1]
Hallo @Thorsten2605 ,
Super Arbeit die du bisher hier in das Node gesteckt hast!
Ich habe das Node auch schon erfolgreich im Einsatz. :sparkling_heart:

--------------------------------------------------------

Hier hätte ich das passende [icon](https://user-images.githubusercontent.com/32074970/69142967-39579700-0ac8-11ea-8f14-b66b9631ee1c.png) für die Nodes:
![Neato](https://user-images.githubusercontent.com/32074970/69142967-39579700-0ac8-11ea-8f14-b66b9631ee1c.png)

--------------------------------------------------------

:memo: 
Vielleicht die ein oder andere Beschreibung wäre auch nicht schlecht :wink:

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Unter der Map Ausgabe wäre vielleicht eine Automatische Ausgabe der Saugzeit unter Berücksichtigung von suspended_cleaning_charging_count;time_in_suspended_cleaning;time_in_error;time_in_pause
wäre nicht schlecht (besitzt die App auch). 

> clean_time:(in min)

etwar so...:

```
id: ""
url: ""
url_valid_for_seconds: 300
version: 1
generated_at: ""
status: "complete"
launched_from: "app"
error: null
modifier: 1
start_at: "2019-11-19T10:52:35Z"
end_at: "2019-11-19T11:21:48Z"
end_orientation_relative_degrees: 1
run_charge_at_start: 99
run_charge_at_end: 33
persistent_map_id: null
cleaned_with_persistent_map_id: ""
suspended_cleaning_charging_count: 0
time_in_suspended_cleaning: 0
time_in_error: 0
time_in_pause: 0
cleaned_area: 24.7584
clean_time: 29
base_count: 1
is_docked: true
delocalized: false
valid_as_persistent_map: false
category: 4
mode: 1
navigation_mode: 2
```

**Comment by Thorsten2605** [comment]
Vielen Dank für die Rückmeldung!

Das Icon werde ich in der nächsten Version einpflegen.

Die Ausgabe der zusätzlichen Informationen bitte selbst über die Dashboard-Elemente einfügen.
Eine zwingende Anzeige bringt nicht jedem Nutzer etwas. Mich interessiert zum Beispiel nur die Quadratmeterzahl und Datum der letzten Reinigung.
Die Map ist direkt aus der dahinter liegenden AWS Cloud entnommen. Dort gibt es keine Möglichkeit weitere Elemente direkt in das Bild zu übernehmen.
